name: Build traceability graph

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python traceability.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GIT_CONFIG_NAME: Code for IATI bot
          GIT_CONFIG_EMAIL: 57559326+codeforIATIbot@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
